//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public string invoiceNO { get; set; }
        public string date { get; set; }
        public int quantity { get; set; }
        public int id_item { get; set; }
        public int id_store { get; set; }
    
        public virtual item item { get; set; }
        public virtual store store { get; set; }
    }
}
